name: canvas_engine
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  lints: ^5.0.0